# Project: GeminiGraph
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o textureloader.o glinterface.o color.o coord.o pendopo.o listtexture.o scene.o
LINKOBJ  = main.o textureloader.o glinterface.o color.o coord.o pendopo.o listtexture.o scene.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -lopengl32 -lfreeglut -lglu32 -lopengl32 -lfreeglut -lglu32
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = GeminiGraph.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CPP) -c main.c -o main.o $(CXXFLAGS)

textureloader.o: textureloader.cpp
	$(CPP) -c textureloader.cpp -o textureloader.o $(CXXFLAGS)

glinterface.o: glinterface.c
	$(CPP) -c glinterface.c -o glinterface.o $(CXXFLAGS)

color.o: color.c
	$(CPP) -c color.c -o color.o $(CXXFLAGS)

coord.o: coord.c
	$(CPP) -c coord.c -o coord.o $(CXXFLAGS)

pendopo.o: pendopo.c
	$(CPP) -c pendopo.c -o pendopo.o $(CXXFLAGS)

listtexture.o: listtexture.c
	$(CPP) -c listtexture.c -o listtexture.o $(CXXFLAGS)

scene.o: scene.c
	$(CPP) -c scene.c -o scene.o $(CXXFLAGS)
